version: '3.5'

services:

  app:
    build: 
      context: .
      target: dev
    container_name: 55ppr-second
    volumes:
      - .:/usr/src/app
      - frontend_node_modules:/usr/src/app/node_modules
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - WEB_PORT=${WEB_PORT}
    entrypoint: npm run dev


volumes:
    frontend_node_modules:
